#!/usr/bin/env python3
"""
generate_regions.py — Generate region_catalog SQL seed from ecoinvent Geographies.xml

Usage:
    python scripts/generate_regions.py path/to/Geographies.xml > /tmp/regions_insert.sql

Writes INSERT INTO region_catalog ... ON CONFLICT DO NOTHING statements to stdout.
Prints a row count summary to stderr when done.

Actual Geographies.xml structure (ecoinvent EcoSpold02):
    Both <name> and <shortname> are CHILD ELEMENTS with xml:lang="en",
    not attributes of <geography>.  Example:

        <geography id="fd6f25d2-..." xmlns="http://www.EcoInvent.org/EcoSpold02">
            <name xml:lang="en">Middle East</name>
            <shortname xml:lang="en">RME</shortname>
            <kml />
        </geography>

Heuristic for is_ecoinvent_shortcut:
    TRUE  — shortname is NOT a 2-letter all-alpha ISO 3166-1 alpha-2 code.
            Covers ecoinvent virtual/aggregate geographies (GLO, RoW, RER,
            RNA, RME, RoE, …), sub-national codes (CA-QC, IN-GJ, IN-TN),
            and multi-word names (Europe without Switzerland).
    FALSE — shortname is exactly 2 alphabetic characters (DE, CN, US, CH, …)
"""

import argparse
import sys
import xml.etree.ElementTree as ET

# The xml:lang attribute expands to this Clark-notation form in ElementTree.
_XML_LANG = "{http://www.w3.org/XML/1998/namespace}lang"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _local_tag(tag: str) -> str:
    """Strip XML namespace prefix from a Clark-notation tag, e.g. '{ns}name' → 'name'."""
    return tag.split("}", 1)[-1] if "}" in tag else tag


def _is_shortcut(shortname: str) -> bool:
    """Return True for ecoinvent virtual/aggregate geographies (non-ISO-3166-1-alpha-2)."""
    return len(shortname) != 2 or not shortname.isalpha()


def _escape(text: str) -> str:
    """Escape single quotes for SQL string literals (standard SQL escaping)."""
    return text.replace("'", "''")


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def parse_geographies(xml_path: str) -> list[tuple[str, str, bool]]:
    """
    Parse Geographies.xml and return a sorted list of (code, name, is_shortcut) tuples.

    Handles both namespaced and plain XML.  The English name is taken from the
    first child element whose local tag is 'name' and whose xml:lang == 'en'.
    Falls back to the shortname itself if no English name is found.
    """
    try:
        tree = ET.parse(xml_path)
    except FileNotFoundError:
        print(f"error: file not found: {xml_path}", file=sys.stderr)
        sys.exit(1)
    except ET.ParseError as exc:
        print(f"error: XML parse failure: {exc}", file=sys.stderr)
        sys.exit(1)

    root = tree.getroot()
    rows: list[tuple[str, str, bool]] = []

    for geo in root.iter():
        if _local_tag(geo.tag) != "geography":
            continue

        # In ecoinvent's EcoSpold02 Geographies.xml both <name> and <shortname>
        # are child elements with xml:lang="en", NOT attributes of <geography>.
        shortname: str | None = None
        en_name: str | None = None
        for child in geo:
            local = _local_tag(child.tag)
            lang  = child.get(_XML_LANG)
            text  = (child.text or "").strip() or None
            if local == "shortname" and lang == "en":
                shortname = text
            elif local == "name" and lang == "en":
                en_name = text

        if not shortname:
            continue

        rows.append((shortname, en_name or shortname, _is_shortcut(shortname)))

    # Sort by code for deterministic, diff-friendly output.
    rows.sort(key=lambda r: r[0].casefold())
    return rows


# ---------------------------------------------------------------------------
# SQL emission
# ---------------------------------------------------------------------------

_HEADER = """\
-- =============================================================================
-- region_catalog seed — generated by scripts/generate_regions.py
-- Source: ecoinvent Geographies.xml
-- Do NOT edit manually — re-run the script to regenerate.
-- =============================================================================
"""

_FOOTER_TMPL = (
    "-- {total} rows total  "
    "({shortcuts} ecoinvent shortcuts,  {countries} country / region codes)"
)


def emit_sql(rows: list[tuple[str, str, bool]]) -> None:
    """Write INSERT statements for every row to stdout."""
    print(_HEADER)

    shortcut_count = sum(1 for _, _, s in rows if s)

    for code, name, shortcut in rows:
        print(
            "INSERT INTO region_catalog (code, name, is_ecoinvent_shortcut) "
            f"VALUES ('{_escape(code)}', '{_escape(name)}', {'TRUE' if shortcut else 'FALSE'}) "
            "ON CONFLICT DO NOTHING;"
        )

    print()
    print(
        _FOOTER_TMPL.format(
            total=len(rows),
            shortcuts=shortcut_count,
            countries=len(rows) - shortcut_count,
        )
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Read ecoinvent Geographies.xml and write region_catalog INSERT "
            "statements to stdout."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Example:\n"
            "  python scripts/generate_regions.py data/Geographies.xml \\\n"
            "      > /tmp/regions_insert.sql\n"
            "  psql \"$DATABASE_URL\" -f /tmp/regions_insert.sql"
        ),
    )
    parser.add_argument(
        "xml_path",
        metavar="GEOGRAPHIES_XML",
        help="Path to ecoinvent Geographies.xml",
    )
    args = parser.parse_args()

    rows = parse_geographies(args.xml_path)

    if not rows:
        print("warning: no <geography> elements found — output will be empty.", file=sys.stderr)

    emit_sql(rows)

    shortcut_count = sum(1 for _, _, s in rows if s)
    print(
        f"Done: {len(rows)} rows written to stdout  "
        f"({shortcut_count} ecoinvent shortcuts, "
        f"{len(rows) - shortcut_count} country/region codes).",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
